export const tenses  = ["présent", "passé composé", "imparfait", "futur simple"]

export const dictionary = {
    "être": [
        {
            "tense": "présent",
            "conjugations": {
                "I am": "je suis",
                "you are": "tu es",
                "he is": "il est",
                "she is": "elle est",
                "we are (informal)": "on est",
                "we are": "nous sommes",
                "you are (pl)": "vous êtes",
                "they are (masc)": "ils sont",
                "they are (fem)": "elles sont",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I was": "j'ai été",
                "you were": "tu as été",
                "he was": "il a été",
                "she was": "elle a été",
                "we were (informal)": "on a été",
                "we were": "nous avons été",
                "you were (pl)": "vous avez été",
                "they were (masc)": "ils ont été",
                "they were (fem)": "elles ont été",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I was": "j'étais",
                "you were": "tu étais",
                "he was": "il était",
                "she was": "elle était",
                "we were (informal)": "on était",
                "we were": "nous étions",
                "you were (pl)": "vous étiez",
                "they were (masc)": "ils étaient",
                "they were (fem)": "elles étaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will be": "je serai",
                "you will be": "tu seras",
                "he will be": "il sera",
                "she will be": "elle sera",
                "we will be (informal)": "on sera",
                "we will be": "nous serons",
                "you will be (pl)": "vous serez",
                "they will be (masc)": "ils seront",
                "they will be (fem)": "elles seront",
            },
        },
    ],
    "avoir": [
        {
            "tense": "présent",
            "conjugations": {
                "I have": "j'ai",
                "you have": "tu as",
                "he has": "il a",
                "she has": "elle a",
                "we have (informal)": "on a",
                "we have": "nous avons",
                "you have (pl)": "vous avez",
                "they have (masc)": "ils ont",
                "they have (fem)": "elles ont",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I had": "j'ai eu",
                "you had": "tu as eu",
                "he had": "il a eu",
                "she had": "elle a eu",
                "we had (informal)": "on a eu",
                "we had": "nous avons eu",
                "you had (pl)": "vous avez eu",
                "they had (masc)": "ils ont eu",
                "they had (fem)": "elles ont eu",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I had": "j'avais",
                "you had": "tu avais",
                "he had": "il avait",
                "she had": "elle avait",
                "we had (informal)": "on avait",
                "we had": "nous avions",
                "you had (pl)": "vous aviez",
                "they had (masc)": "ils avaient",
                "they had (fem)": "elles avaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will have": "j'aurai",
                "you will have": "tu auras",
                "he will have": "il aura",
                "she will have": "elle aura",
                "we will have (informal)": "on aura",
                "we will have": "nous aurons",
                "you will have (pl)": "vous aurez",
                "they will have (masc)": "ils auront",
                "they will have (fem)": "elles auront",
            },
        },
    ],
    "faire": [
        {
            "tense": "présent",
            "conjugations": {
                "I do": "je fais",
                "you do": "tu fais",
                "he does": "il fait",
                "she does": "elle fait",
                "we do (informal)": "on fait",
                "we do": "nous faisons",
                "you do (pl)": "vous faites",
                "they do (masc)": "ils font",
                "they do (fem)": "elles font",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I did": "j'ai fait",
                "you did": "tu as fait",
                "he did": "il a fait",
                "she did": "elle a fait",
                "we did (informal)": "on a fait",
                "we did": "nous avons fait",
                "you did (pl)": "vous avez fait",
                "they did (masc)": "ils ont fait",
                "they did (fem)": "elles ont fait",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I did": "je faisais",
                "you did": "tu faisais",
                "he did": "il faisait",
                "she did": "elle faisait",
                "we did (informal)": "on faisait",
                "we did": "nous faisions",
                "you did (pl)": "vous faisiez",
                "they did (masc)": "ils faisaient",
                "they did (fem)": "elles faisaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will do": "je ferais",
                "you will do": "tu feras",
                "he will do": "il fera",
                "she was": "elle fera",
                "we will do (informal)": "on fera",
                "we will do": "nous ferons",
                "you will do (pl)": "vous ferez",
                "they will do (masc)": "ils feront",
                "they will do (fem)": "elles feront",
            },
        },
    ],
    "aller": [
        {
            "tense": "présent",
            "conjugations": {
                "I go": "je vais",
                "you go": "tu vas",
                "he goes": "il va",
                "she goes": "elle va",
                "we go (informal)": "on va",
                "we go": "nous allons",
                "you go (pl)": "vous allez",
                "they go (masc)": "ils vont",
                "they go (fem)": "elles vont",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I went (masc)": "je suis allé",
                "I went (fem)": "je suis allée",
                "you went (masc)": "tu es allé",
                "you went (fem)": "tu es allée",
                "he went": "il est allé",
                "she went": "elle est allée",
                "we went (informal)": "on est allé",
                "we went": "nous sommes allés",
                "you went (pl)": "vous êtes allés",
                "they went (masc)": "ils sont allés",
                "they went (fem)": "elles sont allées",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I went": "j'allais",
                "you went": "tu allais",
                "he went": "il allait",
                "she went": "elle allait",
                "we went (informal)": "on allait",
                "we went": "nous allions",
                "you went (pl)": "vous alliez",
                "they went (masc)": "ils allaient",
                "they went (fem)": "elles allaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will go": "j'irais",
                "you will go": "tu iras",
                "he will go": "il ira",
                "she was": "elle ira",
                "we will go (informal)": "on ira",
                "we will go": "nous irons",
                "you will go (pl)": "vous irez",
                "they will go (masc)": "ils iront",
                "they will go (fem)": "elles iront",
            },
        },
    ],
    "pouvoir": [
        {
            "tense": "présent",
            "conjugations": {
                "I can": "je peux",
                "you can": "tu peux",
                "he can": "il peut",
                "she can": "elle peut",
                "we can (informal)": "on peut",
                "we can": "nous pouvons",
                "you can (pl)": "vous pouvez",
                "they can (masc)": "ils peuvent",
                "they can (fem)": "elles peuvent",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I could": "j'ai pu",
                "you could": "tu as pu",
                "he could": "il a pu",
                "she could": "elle a pue",
                "we could (informal)": "on a pu",
                "we could": "nous avons pu",
                "you could (pl)": "vous avez pu",
                "they could (masc)": "ils ont pu",
                "they could (fem)": "elles ont pu",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I could": "je pouvais",
                "you could": "tu pouvais",
                "he could": "il pouvait",
                "she could": "elle pouvait",
                "we could (informal)": "on pouvait",
                "we could": "nous pouvions",
                "you could (pl)": "vous pouviez",
                "they could (masc)": "ils pouvaient",
                "they could (fem)": "elles pouvaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will be able to": "je pourrais",
                "you will be able to": "tu pourras",
                "he will be able to": "il pourra",
                "she was": "elle pourra",
                "we will be able to (informal)": "on pourra",
                "we will be able to": "nous pourrons",
                "you will be able to (pl)": "vous pourrez",
                "they will be able to (masc)": "ils pourront",
                "they will be able to (fem)": "elles pourront",
            },
        },
    ],
}
