export const tenses = ["présent", "passé composé", "imparfait", "futur simple"]

export const dictionary = {
    "être": [
        {
            "tense": "présent",
            "conjugations": {
                "I am": "je suis",
                "you are": "tu es",
                "he is": "il est",
                "she is": "elle est",
                "we are (informal)": "on est",
                "we are": "nous sommes",
                "you are (pl)": "vous êtes",
                "they are (masc)": "ils sont",
                "they are (fem)": "elles sont",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I was": "j'ai été",
                "you were": "tu as été",
                "he was": "il a été",
                "she was": "elle a été",
                "we were (informal)": "on a été",
                "we were": "nous avons été",
                "you were (pl)": "vous avez été",
                "they were (masc)": "ils ont été",
                "they were (fem)": "elles ont été",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I was": "j'étais",
                "you were": "tu étais",
                "he was": "il était",
                "she was": "elle était",
                "we were (informal)": "on était",
                "we were": "nous étions",
                "you were (pl)": "vous étiez",
                "they were (masc)": "ils étaient",
                "they were (fem)": "elles étaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will be": "je serai",
                "you will be": "tu seras",
                "he will be": "il sera",
                "she will be": "elle sera",
                "we will be (informal)": "on sera",
                "we will be": "nous serons",
                "you will be (pl)": "vous serez",
                "they will be (masc)": "ils seront",
                "they will be (fem)": "elles seront",
            },
        },
    ],
    "avoir": [
        {
            "tense": "présent",
            "conjugations": {
                "I have": "j'ai",
                "you have": "tu as",
                "he has": "il a",
                "she has": "elle a",
                "we have (informal)": "on a",
                "we have": "nous avons",
                "you have (pl)": "vous avez",
                "they have (masc)": "ils ont",
                "they have (fem)": "elles ont",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I had": "j'ai eu",
                "you had": "tu as eu",
                "he had": "il a eu",
                "she had": "elle a eu",
                "we had (informal)": "on a eu",
                "we had": "nous avons eu",
                "you had (pl)": "vous avez eu",
                "they had (masc)": "ils ont eu",
                "they had (fem)": "elles ont eu",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I had": "j'avais",
                "you had": "tu avais",
                "he had": "il avait",
                "she had": "elle avait",
                "we had (informal)": "on avait",
                "we had": "nous avions",
                "you had (pl)": "vous aviez",
                "they had (masc)": "ils avaient",
                "they had (fem)": "elles avaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will have": "j'aurai",
                "you will have": "tu auras",
                "he will have": "il aura",
                "she will have": "elle aura",
                "we will have (informal)": "on aura",
                "we will have": "nous aurons",
                "you will have (pl)": "vous aurez",
                "they will have (masc)": "ils auront",
                "they will have (fem)": "elles auront",
            },
        },
    ],
    "faire": [
        {
            "tense": "présent",
            "conjugations": {
                "I do": "je fais",
                "you do": "tu fais",
                "he does": "il fait",
                "she does": "elle fait",
                "we do (informal)": "on fait",
                "we do": "nous faisons",
                "you do (pl)": "vous faites",
                "they do (masc)": "ils font",
                "they do (fem)": "elles font",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I did": "j'ai fait",
                "you did": "tu as fait",
                "he did": "il a fait",
                "she did": "elle a fait",
                "we did (informal)": "on a fait",
                "we did": "nous avons fait",
                "you did (pl)": "vous avez fait",
                "they did (masc)": "ils ont fait",
                "they did (fem)": "elles ont fait",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I did": "je faisais",
                "you did": "tu faisais",
                "he did": "il faisait",
                "she did": "elle faisait",
                "we did (informal)": "on faisait",
                "we did": "nous faisions",
                "you did (pl)": "vous faisiez",
                "they did (masc)": "ils faisaient",
                "they did (fem)": "elles faisaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will do": "je ferai",
                "you will do": "tu feras",
                "he will do": "il fera",
                "she was": "elle fera",
                "we will do (informal)": "on fera",
                "we will do": "nous ferons",
                "you will do (pl)": "vous ferez",
                "they will do (masc)": "ils feront",
                "they will do (fem)": "elles feront",
            },
        },
    ],
    "aller": [
        {
            "tense": "présent",
            "conjugations": {
                "I go": "je vais",
                "you go": "tu vas",
                "he goes": "il va",
                "she goes": "elle va",
                "we go (informal)": "on va",
                "we go": "nous allons",
                "you go (pl)": "vous allez",
                "they go (masc)": "ils vont",
                "they go (fem)": "elles vont",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I went (masc)": "je suis allé",
                "I went (fem)": "je suis allée",
                "you went (masc)": "tu es allé",
                "you went (fem)": "tu es allée",
                "he went": "il est allé",
                "she went": "elle est allée",
                "we went (informal)": "on est allé",
                "we went": "nous sommes allés",
                "you went (pl)": "vous êtes allés",
                "they went (masc)": "ils sont allés",
                "they went (fem)": "elles sont allées",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I went": "j'allais",
                "you went": "tu allais",
                "he went": "il allait",
                "she went": "elle allait",
                "we went (informal)": "on allait",
                "we went": "nous allions",
                "you went (pl)": "vous alliez",
                "they went (masc)": "ils allaient",
                "they went (fem)": "elles allaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will go": "j'irai",
                "you will go": "tu iras",
                "he will go": "il ira",
                "she was": "elle ira",
                "we will go (informal)": "on ira",
                "we will go": "nous irons",
                "you will go (pl)": "vous irez",
                "they will go (masc)": "ils iront",
                "they will go (fem)": "elles iront",
            },
        },
    ],
    "pouvoir": [
        {
            "tense": "présent",
            "conjugations": {
                "I can": "je peux",
                "you can": "tu peux",
                "he can": "il peut",
                "she can": "elle peut",
                "we can (informal)": "on peut",
                "we can": "nous pouvons",
                "you can (pl)": "vous pouvez",
                "they can (masc)": "ils peuvent",
                "they can (fem)": "elles peuvent",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I could": "j'ai pu",
                "you could": "tu as pu",
                "he could": "il a pu",
                "she could": "elle a pue",
                "we could (informal)": "on a pu",
                "we could": "nous avons pu",
                "you could (pl)": "vous avez pu",
                "they could (masc)": "ils ont pu",
                "they could (fem)": "elles ont pu",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I could": "je pouvais",
                "you could": "tu pouvais",
                "he could": "il pouvait",
                "she could": "elle pouvait",
                "we could (informal)": "on pouvait",
                "we could": "nous pouvions",
                "you could (pl)": "vous pouviez",
                "they could (masc)": "ils pouvaient",
                "they could (fem)": "elles pouvaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will be able to": "je pourrais",
                "you will be able to": "tu pourras",
                "he will be able to": "il pourra",
                "she was": "elle pourra",
                "we will be able to (informal)": "on pourra",
                "we will be able to": "nous pourrons",
                "you will be able to (pl)": "vous pourrez",
                "they will be able to (masc)": "ils pourront",
                "they will be able to (fem)": "elles pourront",
            },
        },
    ],
    "vouloir": [
        {
            "tense": "présent",
            "conjugations": {
                "I want": "je veux",
                "you want": "tu veux",
                "he wants": "il veut",
                "she wants": "elle veut",
                "we want (informal)": "on veut",
                "we want": "nous voulons",
                "you want (pl)": "vous voulez",
                "they want (masc)": "ils veulent",
                "they want (fem)": "elles veulent",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I wanted": "j'ai voulu",
                "you wanted": "tu as voulu",
                "he wanted": "il a voulu",
                "she wanted": "elle a voulu",
                "we wanted (informal)": "on a voulu",
                "we wanted": "nous avons voulu",
                "you wanted (pl)": "vous avez voulu",
                "they wanted (masc)": "ils ont voulu",
                "they wanted (fem)": "elles ont voulu",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I wanted": "je voulais",
                "you wanted": "tu voulais",
                "he wanted": "il voulait",
                "she wanted": "elle voulait",
                "we wanted (informal)": "on voulait",
                "we wanted": "nous voulions",
                "you wanted (pl)": "vous vouliez",
                "they wanted (masc)": "ils voulaient",
                "they wanted (fem)": "elles voulaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will want": "je voudrai",
                "you will want": "tu voudras",
                "he will want": "il voudra",
                "she will want": "elle voudra",
                "we will want (informal)": "on voudra",
                "we will want": "nous voudrons",
                "you will want (pl)": "vous voudrez",
                "they will want (masc)": "ils voudront",
                "they will want (fem)": "elles voudront",
            },
        }],
    "devoir": [
        {
            "tense": "présent",
            "conjugations": {
                "I have to": "je dois",
                "you have to": "tu dois",
                "he has to": "il doit",
                "she has to": "elle doit",
                "we have to (informal)": "on doit",
                "we have to": "nous devons",
                "you have to (pl)": "vous devez",
                "they have to (masc)": "ils doivent",
                "they have to (fem)": "elles doivent",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I had to": "j'ai dû",
                "you had to": "tu as dû",
                "he had to": "il a dû",
                "she had to": "elle a dû",
                "we had to (informal)": "on a dû",
                "we had to": "nous avons dû",
                "you had to (pl)": "vous avez dû",
                "they had to (masc)": "ils ont dû",
                "they had to (fem)": "elles ont dû",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I had to": "je devais",
                "you had to": "tu devais",
                "he had to": "il devait",
                "she had to": "elle devait",
                "we had to (informal)": "on devait",
                "we had to": "nous devions",
                "you had to (pl)": "vous deviez",
                "they had to (masc)": "ils devaient",
                "they had to (fem)": "elles devaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will have to": "je devrai",
                "you will have to": "tu devras",
                "he will have to": "il devra",
                "she will have to": "elle devra",
                "we will have to (informal)": "on devra",
                "we will have to": "nous devrons",
                "you will have to (pl)": "vous devrez",
                "they will have to (masc)": "ils devront",
                "they will have to (fem)": "elles devront",
            },
        }],
    "connaître": [
        {
            "tense": "présent",
            "conjugations": {
                "I know (connaître)": "je connais",
                "you know (connaître)": "tu connais",
                "he knows (connaître)": "il connaît",
                "she knows (connaître)": "elle connaît",
                "we know (connaître-informal)": "on connaît",
                "we know (connaître)": "nous connaissons",
                "you know (connaître-pl)": "vous connaissez",
                "they know (connaître-masc)": "ils connaissent",
                "they know (connaître-fem)": "elles connaissent",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I knew (connaître)": "j'ai connu",
                "you knew (connaître)": "tu as connu",
                "he knew (connaître)": "il a connu",
                "she knew (connaître)": "elle a connu",
                "we knew (connaître-informal)": "on a connu",
                "we knew (connaître)": "nous avons connu",
                "you knew (connaître-pl)": "vous avez connu",
                "they knew (connaître-masc)": "ils ont connu",
                "they knew (connaître-fem)": "elles ont connu",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I knew (connaître)": "je connaissais",
                "you knew (connaître)": "tu connaissais",
                "he knew (connaître)": "il connaissait",
                "she knew (connaître)": "elle connaissait",
                "we knew (connaître-informal)": "on connaissait",
                "we knew (connaître)": "nous connaissions",
                "you knew (connaître-pl)": "vous connaissiez",
                "they knew (connaître-masc)": "ils connaissaient",
                "they knew (connaître-fem)": "elles connaissaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will know (connaître)": "je connaîtrai",
                "you will know (connaître)": "tu connaîtras",
                "he will know (connaître)": "il connaîtra",
                "she will know (connaître)": "elle connaîtra",
                "we will know (connaître-informal)": "on connaîtra",
                "we will know (connaître)": "nous connaîtrons",
                "you will know (connaître-pl)": "vous connaîtriez",
                "they will know (connaître-masc)": "ils connaîtront",
                "they will know (connaître-fem)": "elles connaîtront",
            },
        }],
    "dire": [
        {
            "tense": "présent",
            "conjugations": {
                "I say": "je dis",
                "you say": "tu dis",
                "he says": "il dit",
                "she says": "elle dit",
                "we say (informal)": "on dit",
                "we say": "nous disons",
                "you say (pl)": "vous dites",
                "they say (masc)": "ils disent",
                "they say (fem)": "elles disent",
            },
        },
        {
            "tense": "passé composé",
            "conjugations": {
                "I said": "j'ai dit",
                "you said": "tu as dit",
                "he said": "il a dit",
                "she said": "elle a dit",
                "we said (informal)": "on a dit",
                "we said": "nous avons dit",
                "you said (pl)": "vous avez dit",
                "they said (masc)": "ils ont dit",
                "they said (fem)": "elles ont dit",
            },
        },
        {
            "tense": "imparfait",
            "conjugations": {
                "I said": "je disais",
                "you said": "tu disais",
                "he said": "il disait",
                "she said": "elle disait",
                "we said (informal)": "on disait",
                "we said": "nous disions",
                "you said (pl)": "vous disiez",
                "they said (masc)": "ils disaient",
                "they said (fem)": "elles disaient",
            },
        },
        {
            "tense": "futur simple",
            "conjugations": {
                "I will say": "je dirai",
                "you will say": "tu diras",
                "he will say": "il dira",
                "she will say": "elle dira",
                "we will say (informal)": "on dira",
                "we will say": "nous dirons",
                "you will say (pl)": "vous direz",
                "they will say (masc)": "ils diront",
                "they will say (fem)": "elles diront",
            },
        }],
}
